-- =============================================================================
-- Homelia — chargement des 9 annonces existantes
-- À exécuter APRÈS schema.sql, dans l'éditeur SQL de Supabase.
-- Relançable sans risque : les lignes déjà présentes sont mises à jour.
-- =============================================================================

insert into public.annonces
  (slug, nom, ville, departement, departement_nom, region, statut, typologies, prix, prix_libelle,
   logements, livraison, accroche, description, specs, prestations, localisation,
   image_url, image2_url, page_statique)
values
  ('communay', 'Le 16 Télégraphe', 'Communay', '69', 'Rhône', 'Auvergne-Rhône-Alpes', 'En vente', 'T3 · T4', '199 000 €', 'à partir de', '12 logements', 'Été 2028', 'Douze maisons de ville neuves avec jardin privatif, au sud de la métropole de Lyon.', 'Le 16 Télégraphe est une résidence de 12 logements neufs en Bail Réel Solidaire, développée par Valdoly Immobilier à Communay, dans la plaine du Rhône au sud de Lyon. Deux bâtiments proposent des maisons de ville T3 et T4 avec jardins privatifs et deux stationnements inclus par logement.

Les surfaces habitables s''échelonnent de 60,44 m² (T3) à 84,47 m² (T4), avec des jardins privatifs de 17 à 94 m² selon les lots. Chaque logement dispose d''une entrée individuelle et d''un jardin attenant.', '["12 logements", "T3 et T4", "Jardin privatif", "2 stationnements"]'::jsonb, '[{"titre": "Jardin privatif attenant", "detail": "Jardin engazonné entièrement privatif, de 17 à 94 m² selon les lots."}, {"titre": "Résidence sécurisée", "detail": "Résidence clôturée avec portail à badge et visiophone pour chaque logement."}, {"titre": "Volets roulants motorisés", "detail": "Sur l''ensemble des ouvertures, pour le confort et la sécurité."}, {"titre": "Climatisation réversible", "detail": "Chauffage en hiver, rafraîchissement en été, inclus dans la prestation."}]'::jsonb, '[{"titre": "En voiture", "points": ["Lyon centre : 25 min", "Accès A7 direct", "Aéroport Saint-Exupéry : 25 min"]}, {"titre": "En transport", "points": ["Gares de Givors ou Solaize à proximité", "Réseau de bus vers la métropole"]}, {"titre": "À proximité", "points": ["Écoles maternelle et primaire à Communay", "Collèges et lycées à Feyzin et Solaize", "Commerces, médecins, pharmacie"]}]'::jsonb, '/assets/img/communay-1.jpg', '/assets/img/communay-2.jpg', '/programmes/communay.html'),
  ('coublevie', 'Les Terrasses des 3 Parcs', 'Coublevie', '38', 'Isère', 'Auvergne-Rhône-Alpes', 'En vente', 'T2 à T5', '129 000 €', 'T2 à partir de', 'Appartements', 'Nous consulter', 'Une résidence au cœur de Coublevie, aux portes du Parc naturel régional de Chartreuse.', 'Les Terrasses des 3 Parcs proposent un cadre de vie entre nature, confort et praticité, à proximité immédiate de Voiron. L''architecture privilégie des intérieurs lumineux et des espaces extérieurs privatifs pour chaque appartement.

Le projet s''accompagne d''espaces paysagers partagés : verger, jardin des sens et cheminements piétons, dans une démarche durable de choix des matériaux et de gestion des ressources.', '["T2 à T5", "Espaces extérieurs", "Verger partagé", "Proche Voiron"]'::jsonb, '[{"titre": "Espaces extérieurs privatifs", "detail": "Chaque appartement est prolongé par un balcon, une terrasse ou un jardin."}, {"titre": "Espaces paysagers partagés", "detail": "Verger partagé, jardin des sens et cheminements piétons au sein de la résidence."}, {"titre": "Stationnement inclus", "detail": "Le prix affiché comprend le stationnement."}, {"titre": "Démarche durable", "detail": "Matériaux responsables et gestion raisonnée des ressources."}]'::jsonb, '[{"titre": "À proximité", "points": ["Commerces, écoles et services à quelques minutes", "Voiron et ses équipements"]}, {"titre": "Cadre", "points": ["Parc naturel régional de Chartreuse", "Environnement naturel préservé"]}]'::jsonb, '/assets/img/coublevie-1.jpg', '/assets/img/coublevie-2.jpg', '/programmes/coublevie.html'),
  ('bourg-saint-christophe', 'Le Domaine des Chênes 2', 'Bourg-Saint-Christophe', '01', 'Ain', 'Auvergne-Rhône-Alpes', 'En vente', 'T4 en duplex', '235 500 €', 'à partir de', 'Maisons en duplex', 'Nous consulter', 'Des maisons en duplex de près de 90 m², à trente kilomètres de Lyon.', 'Le Domaine des Chênes 2 est un programme résidentiel à échelle humaine, conçu pour les familles. Les logements en duplex combinent espace, confort et accessibilité financière grâce au Bail Réel Solidaire.

Chaque maison dispose d''un jardin privatif et d''un garage individuel, dans un environnement calme, à deux minutes du centre-village.', '["T4 duplex", "Près de 90 m²", "Jardin privatif", "Garage individuel"]'::jsonb, '[{"titre": "Jardin privatif", "detail": "Un espace extérieur attenant pour chaque maison."}, {"titre": "Garage individuel", "detail": "Garage fermé compris dans le prix d''acquisition."}, {"titre": "Environnement calme", "detail": "Un cadre résidentiel paisible, dans une commune dynamique."}]'::jsonb, '[{"titre": "En voiture", "points": ["Accès rapide à l''A42 (Lyon / Genève)", "30 km de Lyon"]}, {"titre": "En transport", "points": ["Gare de Meximieux-Pérouges à 10 minutes"]}, {"titre": "À proximité", "points": ["Centre-village et commodités à 2 minutes"]}]'::jsonb, '/assets/img/bourg-st-christophe.jpg', null, '/programmes/bourg-saint-christophe.html'),
  ('frans', 'Green Parc', 'Frans', '01', 'Ain', 'Auvergne-Rhône-Alpes', 'En vente', 'T4', '219 000 €', 'à partir de', '14 pavillons en duplex', 'Nous consulter', 'Quatorze pavillons en duplex avec jardin, entre Villefranche-sur-Saône et Lyon.', 'Green Parc est une résidence à taille humaine de 14 pavillons en duplex, avec jardins privatifs et terrasses, dans un environnement résidentiel à quelques minutes du centre du village.

Sa situation entre Villefranche-sur-Saône et Lyon en fait une adresse recherchée pour les familles qui travaillent dans l''agglomération.', '["14 pavillons", "T4 duplex", "Jardin et terrasse", "Aire de jeux"]'::jsonb, '[{"titre": "Climatisation réversible", "detail": "Chauffage et rafraîchissement inclus dans la prestation."}, {"titre": "Volets roulants motorisés", "detail": "Sur l''ensemble des ouvertures."}, {"titre": "Résidence sécurisée", "detail": "Portail et visiophone, stationnements privatifs."}, {"titre": "Aire de jeux", "detail": "Un espace de jeux aménagé au sein de la résidence."}]'::jsonb, '[{"titre": "À proximité", "points": ["Centre du village et commodités à quelques minutes"]}, {"titre": "Situation", "points": ["Entre Villefranche-sur-Saône et Lyon", "Environnement résidentiel paisible"]}]'::jsonb, '/assets/img/frans.jpg', null, '/programmes/frans.html'),
  ('savigneux', 'L''Orée des champs', 'Savigneux', '01', 'Ain', 'Auvergne-Rhône-Alpes', 'En vente', 'T4', '225 000 €', 'à partir de', 'Maisons T4', 'Nous consulter', 'Des T4 avec terrasse et jardin, au cœur d''un village de l''Ain.', 'L''Orée des champs propose des logements spacieux de type T4 avec terrasse et jardin privatif, pensés pour les familles en quête de tranquillité.

Implantée au cœur du village, à quinze minutes de Villefranche-sur-Saône, la résidence offre un environnement verdoyant où l''école et les commerces sont accessibles à pied.', '["T4", "Terrasse", "Jardin privatif", "2 stationnements"]'::jsonb, '[{"titre": "Terrasse et jardin privatif", "detail": "Un espace extérieur attenant pour chaque logement."}, {"titre": "2 stationnements inclus", "detail": "Deux places attribuées par logement."}]'::jsonb, '[{"titre": "À pied", "points": ["École et commerces du village"]}, {"titre": "En voiture", "points": ["Villefranche-sur-Saône : 15 min", "Accès à l''agglomération lyonnaise"]}]'::jsonb, '/assets/img/savigneux.jpg', null, '/programmes/savigneux.html'),
  ('saint-julien', 'Le Clos Chopin', 'Saint-Julien', '69', 'Rhône', 'Auvergne-Rhône-Alpes', 'En vente', 'T4 en duplex', '257 500 €', 'à partir de', '8 logements', 'Nous consulter', 'Huit maisons en duplex avec vue sur les monts du Beaujolais.', 'Le Clos Chopin est une résidence intimiste de 8 logements en duplex, pensés pour les familles à la recherche d''espace et de confort : près de 100 m² habitables, sur des parcelles pouvant atteindre 450 m².

Chaque maison dispose d''un jardin privatif et d''une vue dégagée sur les monts du Beaujolais.', '["8 logements", "Près de 100 m²", "Parcelles jusqu''à 450 m²", "Garage"]'::jsonb, '[{"titre": "Jardin privatif", "detail": "Parcelles jusqu''à 450 m² selon les lots."}, {"titre": "Garage", "detail": "Garage fermé et place de stationnement."}]'::jsonb, '[{"titre": "À proximité", "points": ["Centre-village à 2 minutes"]}, {"titre": "En voiture", "points": ["Gare et autoroute A6 à 10 minutes", "Villefranche-sur-Saône et agglomération lyonnaise"]}]'::jsonb, '/assets/img/st-julien.jpg', '/assets/img/st-julien-2.jpg', '/programmes/saint-julien.html'),
  ('la-chapelle-de-guinchay', 'Le Bois de la Croix', 'La Chapelle-de-Guinchay', '71', 'Saône-et-Loire', 'Bourgogne-Franche-Comté', 'En vente', 'T4 duplex jumelés', '185 000 €', 'à partir de', 'Maisons jumelées', 'Nous consulter', 'Des maisons jumelées en duplex, entre Mâcon et Belleville-en-Beaujolais.', 'Le Bois de la Croix est un programme à taille humaine de maisons jumelées en duplex, avec terrasse et jardin privatifs.

Sa situation entre Mâcon et Belleville-en-Beaujolais offre un cadre paisible, à proximité immédiate des services du quotidien.', '["T4 duplex", "Terrasse et jardin", "Garage", "Finitions personnalisables"]'::jsonb, '[{"titre": "Garage et stationnement", "detail": "Inclus dans le prix d''acquisition."}, {"titre": "Finitions personnalisables", "detail": "Le choix des finitions se fait avec vous, avant travaux."}, {"titre": "Espaces extérieurs", "detail": "Terrasse et jardin privatifs pour chaque maison."}]'::jsonb, '[{"titre": "À proximité", "points": ["Centre-ville et commodités"]}, {"titre": "Situation", "points": ["Entre Mâcon et Belleville-en-Beaujolais"]}]'::jsonb, '/assets/img/chapelle-guinchay.jpg', null, '/programmes/la-chapelle-de-guinchay.html'),
  ('bassens', 'Camberia', 'Bassens', '73', 'Savoie', 'Auvergne-Rhône-Alpes', 'En vente', 'T2 · T3', '153 000 €', 'T2 à partir de', 'Appartements', 'Nous consulter', 'Le calme d''une commune résidentielle, à la porte de Chambéry.', 'Camberia est implantée à Bassens, commune résidentielle qui jouxte Chambéry : le calme d''un village, avec l''énergie et les services d''une ville-centre.

Tous les appartements sont prolongés par un espace extérieur, et les intérieurs offrent des espaces de vie idéalement orientés et baignés de lumière.', '["T2 et T3", "Espace extérieur", "Stationnement et cave", "Proche Chambéry"]'::jsonb, '[{"titre": "Espace extérieur pour chaque appartement", "detail": "Balcon ou terrasse selon les lots."}, {"titre": "Stationnement et cave inclus", "detail": "Compris dans le prix affiché."}, {"titre": "Finitions personnalisables", "detail": "Personnalisation possible des finitions."}]'::jsonb, '[{"titre": "En transport", "points": ["Réseau Synchro Bus"]}, {"titre": "À proximité", "points": ["Commerces et supermarchés", "Écoles et équipements sportifs", "Services de santé"]}, {"titre": "Cadre", "points": ["Vues sur les reliefs", "Proximité immédiate de Chambéry"]}]'::jsonb, '/assets/img/bassens.jpg', null, '/programmes/bassens.html'),
  ('drancy', 'L''Essentiel', 'Drancy', '93', 'Seine-Saint-Denis', 'Île-de-France', 'En vente', 'T2 · T3', '169 000 €', 'T2 à partir de', 'Appartements', 'Nous consulter', 'Une résidence contemporaine du quartier Paris Campagne, aux portes de Paris.', 'L''Essentiel s''intègre au quartier Paris Campagne à Drancy : une architecture élégante, des espaces extérieurs généreux et des prestations soignées.

Les appartements bénéficient de belles ouvertures et se prolongent par un balcon, une loggia ou un jardin privatif, dans un environnement verdoyant.', '["T2 et T3", "Balcon ou loggia", "Stationnement inclus", "Quartier Paris Campagne"]'::jsonb, '[{"titre": "Balcon, loggia ou jardin", "detail": "Un espace extérieur pour chaque appartement."}, {"titre": "Stationnement inclus", "detail": "Compris dans le prix affiché."}, {"titre": "Environnement verdoyant", "detail": "Un quartier paysager, aux portes de Paris."}]'::jsonb, '[{"titre": "À proximité", "points": ["Commerces, transports et équipements urbains"]}, {"titre": "Situation", "points": ["Quartier Paris Campagne", "Accès rapide à Paris"]}]'::jsonb, '/assets/img/drancy.jpg', null, '/programmes/drancy.html'),
  ('gleize', 'Via Edena', 'Gleizé', '69', 'Rhône', 'Auvergne-Rhône-Alpes', 'En vente', 'T4 · T5', '277 000 €', 'T4 en duplex à partir de', 'Maisons', 'Nous consulter', 'Un nouveau quartier pavillonnaire à huit minutes du centre de Villefranche-sur-Saône.', 'À seulement 8 minutes du centre de Villefranche-sur-Saône, Gleizé déploie un cadre de vie empreint de sérénité. Au cœur d''un secteur paisible, bordé de paysages au charme préservé, un nouveau quartier pavillonnaire prend forme, conçu comme un univers où la nature est omniprésente.

Les maisons de 4 ou 5 pièces dévoilent des surfaces généreuses et des agencements soigneusement conçus pour aménager chaque espace selon vos envies. Chacune s''ouvre sur un jardin privatif, prolongé d''une terrasse ombragée par une pergola.', '["Maisons T4 et T5", "Duplex avec jardin", "Garage + stationnement", "Terrasse et pergola"]'::jsonb, '[{"titre": "Jardin privatif et pergola", "detail": "Chaque maison s''ouvre sur un jardin privatif prolongé d''une terrasse ombragée par une pergola."}, {"titre": "Garage et stationnement", "detail": "Un garage et une place de stationnement sont compris dans le prix affiché."}, {"titre": "Maisons en duplex", "detail": "Des T4 et T5 sur deux niveaux, aux surfaces généreuses et aux agencements modulables."}, {"titre": "Quartier pavillonnaire neuf", "detail": "Un secteur paisible bordé de paysages préservés, aux portes de Villefranche-sur-Saône."}]'::jsonb, '[{"titre": "En voiture", "points": ["Centre de Villefranche-sur-Saône : 8 min", "Accès A6 par Villefranche", "Lyon : environ 45 min"]}, {"titre": "À proximité", "points": ["Commerces, écoles et services de Gleizé", "Équipements de Villefranche-sur-Saône"]}, {"titre": "Cadre", "points": ["Secteur pavillonnaire calme", "Paysages du Beaujolais"]}]'::jsonb, '/assets/img/gleize-1.jpg', '/assets/img/gleize-2.jpg', '/programmes/gleize.html'),
  ('les-cheres', 'Côme', 'Les Chères', '69', 'Rhône', 'Auvergne-Rhône-Alpes', 'En vente', 'T2 à T4', '159 400 €', 'T2 à partir de', '18 appartements', 'Nous consulter', 'Dix-huit appartements dans un village authentique, à vingt minutes de l''entrée de Lyon.', 'Idéalement située à 20 minutes de l''entrée de Lyon, Côme propose 18 appartements du 2 au 4 pièces. Cette résidence intimiste s''intègre dans un cadre pavillonnaire calme et verdoyant, au cœur du village des Chères, à quelques pas des commerces, des écoles et des transports.

Pensée comme un lieu de vie apaisant et contemporain, Côme séduit par ses lignes douces, ses teintes naturelles et son architecture soignée. Chaque logement bénéficie d''un extérieur privatif — balcon, terrasse ou jardin — et d''au moins une place de stationnement incluse dans le prix.', '["18 appartements", "T2 à T4", "Extérieur privatif", "Stationnement inclus"]'::jsonb, '[{"titre": "Extérieur privatif", "detail": "Un balcon, une terrasse ou un jardin pour chaque appartement."}, {"titre": "Stationnement inclus", "detail": "Au moins une place de stationnement comprise dans le prix affiché."}, {"titre": "Résidence intimiste", "detail": "Dix-huit logements seulement, dans un cadre pavillonnaire calme et verdoyant."}, {"titre": "Architecture soignée", "detail": "Des lignes douces, des teintes naturelles et des espaces ouverts et lumineux."}]'::jsonb, '[{"titre": "En voiture", "points": ["Entrée de Lyon : 20 min", "Villefranche-sur-Saône à proximité"]}, {"titre": "En transport", "points": ["Arrêt de bus à 5 min à pied", "Liaisons vers Lyon et Villefranche-sur-Saône"]}, {"titre": "À proximité", "points": ["Commerces du village", "Écoles et transports en commun"]}]'::jsonb, '/assets/img/lescheres-1.jpg', '/assets/img/lescheres-2.jpg', '/programmes/les-cheres.html'),
  ('thorigne-fouillard', 'Serenia', 'Thorigné-Fouillard', '35', 'Ille-et-Vilaine', 'Bretagne', 'En vente', 'T2 · T3', '159 900 €', 'T2 à partir de', 'Appartements', 'Nous consulter', 'Notre adresse bretonne, dans la première couronne de Rennes.', 'Au cœur de Thorigné-Fouillard, l''adresse séduit par son cadre de vie agréable et pratique : le calme d''une petite ville et les avantages d''une grande agglomération toute proche. La ligne de bus 50 rejoint le métro rennais en 15 minutes.

Le quartier est particulièrement apprécié des familles : commerces de proximité, cadre verdoyant avec le parc pédagogique de la Juteauderie et ses potagers associatifs, et des projets d''aménagement qui préservent l''équilibre entre logements neufs et espaces naturels.', '["T2 et T3", "Stationnement inclus", "Bus 50 vers le métro", "Première couronne rennaise"]'::jsonb, '[{"titre": "Stationnement inclus", "detail": "Une place de stationnement comprise dans le prix affiché."}, {"titre": "À 15 minutes du métro", "detail": "La ligne de bus 50 rejoint le métro rennais en un quart d''heure."}, {"titre": "Commerces de proximité", "detail": "Boulangeries, services et équipements à quelques pas de la résidence."}, {"titre": "Un quartier verdoyant", "detail": "Le parc pédagogique de la Juteauderie, ses potagers associatifs et ses petits animaux."}]'::jsonb, '[{"titre": "En transport", "points": ["Bus 50 : métro rennais en 15 min", "Rennes centre à proximité"]}, {"titre": "À proximité", "points": ["Commerces de proximité et boulangeries", "Écoles et équipements de la commune"]}, {"titre": "Cadre", "points": ["Parc pédagogique de la Juteauderie", "Première couronne de Rennes"]}]'::jsonb, '/assets/img/thorigne-1.jpg', '/assets/img/thorigne-2.jpg', '/programmes/thorigne-fouillard.html')
on conflict (slug) do update set
  nom = excluded.nom, ville = excluded.ville, departement = excluded.departement,
  departement_nom = excluded.departement_nom, region = excluded.region, statut = excluded.statut,
  typologies = excluded.typologies, prix = excluded.prix, prix_libelle = excluded.prix_libelle,
  logements = excluded.logements, livraison = excluded.livraison, accroche = excluded.accroche,
  description = excluded.description, specs = excluded.specs, prestations = excluded.prestations,
  localisation = excluded.localisation, image_url = excluded.image_url,
  image2_url = excluded.image2_url, page_statique = excluded.page_statique;

-- Ordre d'affichage et mise en avant dans le carrousel de la page d'accueil
update public.annonces set ordre = 10, mis_en_avant = true  where slug in ('communay', 'coublevie', 'bourg-saint-christophe', 'frans', 'saint-julien');
update public.annonces set ordre = 50, mis_en_avant = false where mis_en_avant is not true;

-- =============================================================================
-- Compte responsable
-- 1. Authentication → Users → Add user → e-mail contact@homelia-accession.fr,
--    cocher « Auto Confirm User », choisir le mot de passe.
-- 2. Puis exécuter la ligne ci-dessous pour lui donner le rôle responsable :
-- =============================================================================
-- update public.profils set role = 'responsable'
-- where id = (select id from auth.users where email = 'contact@homelia-accession.fr');
